---
version: "2.0"

services:
  dbms:
    build:
      context: .
      dockerfile: postgresql/Dockerfile
      args:
        IRODS_RESOURCES: "$IRODS_RES_CONF_NAME:$IRODS_CONF_HOST:$IRODS_VAULT"
        IRODS_ZONE_NAME: "$IRODS_ZONE_NAME"
        DB_NAME: "$DB_NAME"
        DB_USER: "$DB_USER"
        DB_PASSWORD: "$DB_PASSWORD"
        DBMS_PORT: "$DBMS_PORT"
        IRODS_ADMIN_USER: "$IRODS_ADMIN_USER"
        IRODS_ADMIN_PASSWORD: "$IRODS_ADMIN_PASSWORD"
        IRODS_BISQUE_ADMIN_USER: "$IRODS_BISQUE_ADMIN_USER"
        IRODS_BISQUE_ADMIN_PASSWORD: "$IRODS_BISQUE_ADMIN_PASSWORD"
    volumes:
      - "db_volume:/var/lib/postgresql/12/main"
      - "db_backup_volume:/var/opt/db_backup"

  nats:
    image: nats-streaming:0.24.6
    command:
      - "--cluster_id"
      - "$NATS_CLUSTER_ID"
      - "--cluster_log_path"
      - "/data/log"
      - "--dir"
      - "/data/msg"
      - "--http_port"
      - "$NATS_MANAGEMENT_PORT"
      - "--port"
      - "$NATS_PORT"
      - "--store"
      - "file"
    hostname: "$NATS_CONF_HOST"
    ports:
      - "$NATS_PORT:$NATS_PORT"
      - "$NATS_MANAGEMENT_PORT:$NATS_MANAGEMENT_PORT"
    volumes:
      - "nats_volume:/data"

  irods:
    build:
      context: .
      dockerfile: irods/Dockerfile
      args:
        DB_NAME: "$DB_NAME"
        DB_USER: "$DB_USER"
        DB_PASSWORD: "$DB_PASSWORD"
        DBMS_HOST: "$DBMS_HOST"
        DBMS_PORT: "$DBMS_PORT"
        DBMS_TYPE: "$DBMS_TYPE"
        IRODS_CONTROL_PLANE_KEY: "$IRODS_CONTROL_PLANE_KEY"
        IRODS_CONTROL_PLANE_PORT: "$IRODS_CONTROL_PLANE_PORT"
        IRODS_DEFAULT_RESOURCE: "$IRODS_DEFAULT_RESOURCE"
        IRODS_FIRST_EPHEMERAL_PORT: "$IRODS_FIRST_EPHEMERAL_PORT"
        IRODS_LAST_EPHEMERAL_PORT: "$IRODS_LAST_EPHEMERAL_PORT"
        IRODS_HOST: "$IRODS_CONF_HOST"
        IRODS_NEGOTIATION_KEY: "$IRODS_NEGOTIATION_KEY"
        IRODS_SCHEMA_VALIDATION: "$IRODS_SCHEMA_VALIDATION"
        IRODS_SYSTEM_GROUP: "$IRODS_SYSTEM_GROUP"
        IRODS_SYSTEM_USER: "$IRODS_SYSTEM_USER"
        IRODS_ZONE_NAME: "$IRODS_ZONE_NAME"
        IRODS_ZONE_KEY: "$IRODS_ZONE_KEY"
        IRODS_ZONE_PORT: "$IRODS_ZONE_PORT"
        IRODS_ADMIN_USER: "$IRODS_ADMIN_USER"
        IRODS_ADMIN_PASSWORD: "$IRODS_ADMIN_PASSWORD"
        IRODS_MAX_NUM_RE_PROCS: "$IRODS_MAX_NUM_RE_PROCS"
    hostname: "$IRODS_CONF_HOST"
    ports:
      - "1247:1247"
      - "$IRODS_FIRST_EPHEMERAL_PORT-$IRODS_LAST_EPHEMERAL_PORT:$IRODS_FIRST_EPHEMERAL_PORT-$IRODS_LAST_EPHEMERAL_PORT"
    volumes:
      - "irods_volume:$IRODS_VAULT"
    depends_on:
      - dbms
      - nats
  
volumes:
  db_volume:
    #external: true
  db_backup_volume:
    #external: true
  nats_volume:
    #external: true
  irods_volume:
    #external: true
    